In [7]:
function [v] = rank(M, d, v_quadratic_error)
 
N = size(M, 2); % N is equal to half the size of M
v = rand(N, 1);
v = v ./ norm(v, 2);
last_v = ones(N, 1) * inf;
M_hat = (d .* M) + (((1 - d) / N) .* ones(N, N));
 
while(norm(v - last_v, 2) > v_quadratic_error)
	last_v = v;
	v = M_hat * v;
	v = v ./ norm(v, 2);
end
 
endfunction

In [8]:
M = [0.00000   0.33333   0.33333   0.33333   0.00000   0.00000   0.00000;
   0.00000   0.00000   0.33333   0.33333   0.33333   0.00000   0.00000;
   0.20000   0.20000   0.00000   0.00000   0.20000   0.20000   0.20000;
   0.20000   0.20000   0.20000   0.00000   0.00000   0.20000   0.20000;
   0.00000   0.00000   0.00000   0.33333   0.00000   0.33333   0.33333;
   0.33333   0.00000   0.00000   0.33333   0.33333   0.00000   0.00000;
   0.25000   0.25000   0.25000   0.00000   0.25000   0.00000   0.00000]

M =

   0.00000   0.33333   0.33333   0.33333   0.00000   0.00000   0.00000
   0.00000   0.00000   0.33333   0.33333   0.33333   0.00000   0.00000
   0.20000   0.20000   0.00000   0.00000   0.20000   0.20000   0.20000
   0.20000   0.20000   0.20000   0.00000   0.00000   0.20000   0.20000
   0.00000   0.00000   0.00000   0.33333   0.00000   0.33333   0.33333
   0.33333   0.00000   0.00000   0.33333   0.33333   0.00000   0.00000
   0.25000   0.25000   0.25000   0.00000   0.25000   0.00000   0.00000



In [9]:
rank2(M, 0.85, 0.001)

ans =

   0.14471
   0.14479
   0.14463
   0.14468
   0.14473
   0.14471
   0.14467



In [12]:
v = [2 6 7 ]
A = zeros(3)
A(diag(A)) = v

diag(v)


v =

   2   6   7

A =

   0   0   0
   0   0   0
   0   0   0

error: A(0): subscripts must be either integers 1 to (2^31)-1 or logicals
ans =

Diagonal Matrix

   2   0   0
   0   6   0
   0   0   7

