In [2]:
x(1,) = 9;
x = [x; 1:4]

error: vertical dimensions mismatch (1x1 vs 1x4)


In [3]:
A = [1 2 3; 2 3 4; 5 6 7]

A =

   1   2   3
   2   3   4
   5   6   7



In [8]:
A = [A ;ones(1,4)]

A =

   1   2   3   1
   2   3   4   1
   5   6   7   1
   1   1   1   1



In [9]:
v = [2 3 3 4]

v =

   2   3   3   4



In [10]:
A = [A;v]

A =

   1   2   3   1
   2   3   4   1
   5   6   7   1
   1   1   1   1
   2   3   3   4



In [15]:
disp(v)

   2   3   3   4
   1   2   3   1
   2   3   4   1
   5   6   7   1
   1   1   1   1
   2   3   3   4
   1   2   3   4
   5   6   6   7
   9   8   7   6


In [12]:
A = [A; B(1:3, :)]

A =

   1   2   3   1
   2   3   4   1
   5   6   7   1
   1   1   1   1
   2   3   3   4
   1   2   3   4
   5   6   6   7
   9   8   7   6



In [14]:
v = [v; A(1:8, :)]

v =

   2   3   3   4
   1   2   3   1
   2   3   4   1
   5   6   7   1
   1   1   1   1
   2   3   3   4
   1   2   3   4
   5   6   6   7
   9   8   7   6



In [16]:
a = [1 2 3]
b =[ 23 4 4]
c = [4 45 6]
d = [a,b,c]

a =

   1   2   3

b =

   23    4    4

c =

    4   45    6

d =

    1    2    3   23    4    4    4   45    6



In [17]:
n = length(d)

n =  9
